// EXPANDED_CULTURE_DESCRIPTOR - Start
#define LANGUAGE_HUMAN_LORRIMAN		"Lirris"
#define LANGUAGE_HUMAN_AVALON		"Alain"
#define LANGUAGE_HUMAN_MIRANIAN		"Miranian"
// EXPANDED_CULTURE_DESCRIPTOR - End
